name: flutterlookfor
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  intl: ^0.20.2
  http: ^1.6.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5
 
  
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.jpg
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.jpg"
  adaptive_icon_background: "#005BAB"
  adaptive_icon_foreground: "assets/icons/app_logo.jpg"

flutter:
  uses-material-design: true

assets:
  - assets/DB_LookFor.db
  - assets/icons/app_logo.jpg
  - assets/icons/splash.jpg
